services:
  playbot:
    image: timoliukko42/discord-playbot:latest
    container_name: playbot
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - youtube_cookies
    volumes:
        - playbot-data:/discord-playbot/playlists
        - playbot-songs:/discord-playbot/songs
    networks:
      - botnet

secrets:
  youtube_cookies:
    file: ./secret/cookies.txt

networks:
  botnet:
    driver: bridge

volumes:
  playbot-data:
  playbot-songs:

